[project]
name = "bitflow-dlmm"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.sip-010-trait-ft-standard-v-1-1]
path = "contracts/external/sip-010-trait-ft-standard-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.sip-013-trait-sft-standard-v-1-1]
path = "contracts/external/sip-013-trait-sft-standard-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.sip-013-transfer-many-trait-v-1-1]
path = "contracts/external/sip-013-transfer-many-trait-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.dlmm-pool-trait-v-1-1]
path = "contracts/dlmm-pool-trait-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.dlmm-core-v-1-1]
path = "contracts/dlmm-core-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.dlmm-pool-sbtc-usdc-v-1-1]
path = "contracts/dlmm-pool-sbtc-usdc-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.dlmm-swap-helper-v-1-1]
path = "contracts/dlmm-swap-helper-v-1-1.clar"
clarity_version = 3
epoch = "3"

[contracts.dlmm-liquidity-helper-v-1-1]
path = "contracts/dlmm-liquidity-helper-v-1-1.clar"
clarity_version = 3
epoch = "3"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet